project:
  type: website
  output-dir: docs

website:
  title: "Tidy Bio"
  open-graph: true
  image: tidybio.png
  favicon: tidybio.png
  navbar:
    logo: tidybio.png
    left:
      - href: index.qmd
        text: Home
      - contact.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/vanessa-chong-morrison
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/vchongmorrison
        aria-label: GitHub
      - icon: mastodon
        href: https://biologists.social/@ChongMorrison
        aria-label: mastodon
      
  page-footer: "Copyright 2025 Tidy Bio Ltd | Company No. 16116809 | VAT GB483258762" 

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: visual

